# Generated by Django 2.1.4 on 2019-01-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_invoice_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'Банковские счета'},
        ),
    ]
