# Generated by Django 2.1.4 on 2019-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190125_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'счет', 'verbose_name_plural': 'Банковские счета'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='num',
            field=models.CharField(max_length=20, verbose_name='Номер'),
        ),
    ]
