# Generated by Django 2.1.4 on 2019-02-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('активна', 'активна'), ('завершена', 'завершена'), ('отменена', 'отменена')], db_index=True, default='активна', max_length=100, verbose_name='Статус')),
                ('time_on_pay_expire', models.DateTimeField(verbose_name='Время на оплату истекает')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_by_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'сделку',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (руб.)')),
                ('limit_hours_on_pay', models.IntegerField(verbose_name='Часов на оплату')),
                ('status', models.CharField(choices=[('доступно', 'доступно'), ('недоступно', 'недоступно')], db_index=True, default='доступно', max_length=100)),
                ('money_to_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Invoice', verbose_name='Деньги на счет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_invoice_provider', models.CharField(max_length=5)),
                ('number_invoice_reciever', models.CharField(max_length=5)),
                ('key', models.CharField(default='', max_length=5)),
                ('amount_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('не подтвержден', 'не подтвержден'), ('оплачен', 'оплачен')], db_index=True, default='не подтвержден', max_length=100)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Deal')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Offer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_by_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
