# Generated by Django 2.1.4 on 2019-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
