# Generated by Django 2.1.4 on 2019-01-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20190121_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'комиссия', 'verbose_name_plural': 'Комиссия'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус сделки', 'verbose_name_plural': 'Статусы сделки'},
        ),
        migrations.AddField(
            model_name='offer',
            name='money_to_invoice',
            field=models.CharField(default='dfer434', max_length=20),
            preserve_default=False,
        ),
    ]
