# Generated by Django 2.1.4 on 2019-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='time_on_pay',
            field=models.DateTimeField(),
        ),
    ]
