# Generated by Django 2.1.4 on 2019-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20190111_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
