# Generated by Django 2.1.4 on 2019-01-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20190111_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
