# Generated by Django 2.1.4 on 2019-01-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20190125_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='money_to_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Invoice'),
        ),
    ]
