# Generated by Django 2.1.4 on 2019-01-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_offer'),
        ('deal', '0004_auto_20190111_0853'),
    ]

    operations = [
    ]
