# Generated by Django 2.1.4 on 2019-01-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_merge_20190114_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='time_on_pay',
            new_name='limit_days_on_pay',
        ),
    ]
