# Generated by Django 2.1.4 on 2019-01-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_merge_20190114_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOffer',
            fields=[
            ],
            options={
                'permissions': (('view_newOffer', 'Can view all offers'),),
                'proxy': True,
                'indexes': [],
            },
            bases=('deal.offer',),
        ),
    ]
