# Generated by Django 2.1.4 on 2019-01-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20190126_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_invoice_provider', models.CharField(max_length=5)),
                ('number_invoice_reciever', models.CharField(max_length=5)),
                ('key', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Deal')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.StatusPayment'),
        ),
    ]
