# Generated by Django 2.1.4 on 2019-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20190127_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_money',
        ),
        migrations.AlterField(
            model_name='payment',
            name='key',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='statuspayment',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
