# Generated by Django 2.1.4 on 2019-01-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_newoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewOffer',
        ),
        migrations.CreateModel(
            name='OfferProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All offer',
                'proxy': True,
                'indexes': [],
            },
            bases=('deal.offer',),
        ),
    ]
