# Generated by Django 2.1.4 on 2019-01-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20190114_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferProxy',
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer'},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='time_on_pay',
            new_name='limit_days_on_pay',
        ),
    ]
