# Generated by Django 2.1.4 on 2019-01-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20190127_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Offer', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='limit_hours_on_pay',
            field=models.IntegerField(verbose_name='Время на оплату'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='money_to_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Invoice', verbose_name='Деньги на счет'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
