# Generated by Django 2.1.4 on 2019-01-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20190114_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferProxy',
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer'},
        ),
    ]
