# Generated by Django 2.1.4 on 2019-01-28 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_auto_20190127_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'сделку', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_by_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Offer', verbose_name='Предложение'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_by_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='time_on_pay_expire',
            field=models.DateTimeField(verbose_name='Время на оплату истекает'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='limit_hours_on_pay',
            field=models.IntegerField(verbose_name='Часов на оплату'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (руб.)'),
        ),
    ]
