# Generated by Django 2.1.4 on 2019-01-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='limit_days_on_pay',
            new_name='limit_hours_on_pay',
        ),
    ]
