# Generated by Django 2.1.4 on 2019-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_auto_20190128_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Не подтвержден', 'Не подтвержден'), ('Оплачен', 'Оплачен')], default='Не подтвержден', max_length=50),
        ),
        migrations.DeleteModel(
            name='StatusPayment',
        ),
    ]
