# Generated by Django 2.1.4 on 2019-02-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_auto_20190201_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('active', 'активна'), ('completed', 'завершена'), ('canceled', 'отменена')], default='active', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Не подтвержден'), ('paid', 'Оплачен')], default='not_confirmed', max_length=50),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
