# Generated by Django 2.1.4 on 2019-02-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0012_auto_20190201_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('доступно', 'доступно'), ('недоступно', 'недоступно')], default='доступно', max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('активна', 'активна'), ('завершена', 'завершена'), ('отменена', 'отменена')], default='активна', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('не подтвержден', 'не подтвержден'), ('оплачен', 'оплачен')], default='не подтвержден', max_length=100),
        ),
    ]
